# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: warp-ubuntu-latest-x64-2x;snapshot.key=my_snapshot

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Read my saved workspace
        run: cat my_keptfile.txt || true
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Runs a set of commands using the runners shell
      - name: Create a file
        run: |
          echo $(date) >> my_keptfile.txt

      - name: Read my saved workspace
        run: cat my_keptfile.txt || true

      - name: Create snapshot
        uses: WarpBuilds/snapshot-save@v1
        with:
          alias: 'my_snapshot'
          fail-on-error: true
          wait-timeout-minutes: 60
